### ISSUE TITLE
Info about `MapChart` constructor is missing in docs

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/node-export-server#128]
https://github.com/highcharts/node-export-server/blame/master/README.md#L75

**Comment by KacperMadej** [comment]
@cvasseng  Looks like `MapChart` is not working - however, `mapChart` seems to work fine. I tried via console.

Additionally, adding map JS (like `https://code.highcharts.com/mapdata/countries/gb/gb-all.js`) in `cdnAdditional` breaks the server when trying to create a chart - maybe file loading order is wrong? so it's just not a good place to add a map file. 

It works fine when the map file is added like:
```js
const cdnMaps = [
    "maps/{{version}}/modules/map.js",
    "mapdata/countries/gb/gb-all.js"
];
```

**Comment by TorsteinHonsi** [comment]
`MapChart` is not defined, it's either `chart = new Highcharts.Map(..)` or `chart = Highcharts.mapChart(..)`. When we added the lower-case-first factory functions, the name `Highcharts.map` was already taken, hence the inconsistency.

https://github.com/highcharts/highcharts/blob/8c1c146ab5bf0dd5bd798d997fc46b7fe75884e2/js/parts-map/Map.js#L396

**Comment by cvasseng** [comment]
I've updated the readme to say `Map` now.

About the map collection - I think we need to add prompting or something on which to include. I'm thinking maybe asking the user to supply an (optional) location for a JSON file with an array of collections to include if building with maps support. There's too many of them to prompt for each, and it needs to be compatible with automated deployments too (e.g. needs to be possible to set it via. env variables or something similar). It could also be possible to set up a `highcharts` object in people's `package.json` with an array of additional things to include, but that would only make sense for people using it as a module.

**Comment by cvasseng** [comment]
BTW - as a workaround for the mapcollection, you should be able to put the collection URL's in the `cdnScriptsOptional` map.

**Comment by KacperMadej** [comment]
@cvasseng 
The server throws error when trying to create a chart after more than a one map is loaded. I tried loading them through `cdnScriptsOptional` using full URL, in `cdnMaps` using short and full. Files are loaded, but during worker's work the error is:
```
phantom worker 1 unexpected data - SyntaxError: Expected an identifier but found 'Highcharts' instead

  phantomjs://code/worker.js:629 in loop
{"filename":"1.png"}
```
The file name is from command used:
`highcharts-export-server --infile options.json --outfile 1.png --constr mapChart`

**Comment by jerang** [comment]
@cvasseng please reopen this, still an issue for us. Could you please take a look?

**Comment by KacperMadej** [comment]
@jerang @cvasseng 
The problem is caused by maps - the .js files are looking like `Highcharts.maps["map_name"] = { ... }` and there's no `;` at the end, so if next map is loaded, then page breaks. As far as I could test this could be resolved by adding `;` between each loaded script. It won't harm other files and will make maps work.

Required change in `build.js` before running `npm link`:
```js
        funs.push(function (next) {
            // If we've allready fetched the required script, just return it.
            if (cachedScripts[fullURL]) {
              console.log(('   using cached fetch for ' + fullURL).gray);
              scriptBody += cachedScripts[fullURL] + ';';
              return next();
            }

            console.log('  ', (fullURL).gray);

            request(fullURL, function (error, response, body) {

                if (error) {
                  if (optionals[scriptOriginal]) {
                    console.log(`  ${script} is not available for v${version}`.gray)
                    return next();
                  }

                  return next(error, fullURL);
                }

                if (body.trim().indexOf('<!DOCTYPE') === 0) {
                  if (optionals[scriptOriginal]) {
                    console.log(`   ${script.substr(script.lastIndexOf('/') + 1)} is not available for v${version}, skipped..`.yellow);
                    return next();
                  }

                  return next(404, script);
                }

                cachedScripts[fullURL] = body;
                scriptBody += body + ';';
                next();
            });
        });
```

so lines change are:
`scriptBody += cachedScripts[fullURL] + ';';`
and
`scriptBody += body + ';';`

After those changes adding maps to `cdnMaps` works.
```js
const cdnMaps = [
    "maps/{{version}}/modules/map.js",
    "https://code.highcharts.com/mapdata/countries/us/us-all.js",
    "https://code.highcharts.com/mapdata/countries/gb/gb-all.js",
    "https://code.highcharts.com/mapdata/custom/world.js",
    "https://code.highcharts.com/mapdata/custom/africa.js"
];
```

**Comment by jerang** [comment]
@KacperMadej that did the trick! Thanks!!
cc @cvasseng

**Comment by andreyfomin** [comment]
Please give example how to generate map chart png file.

**Comment by KacperMadej** [comment]
The `;` was added to all maps in `.js` format in https://github.com/highcharts/map-collection/pull/11 and was published in the current Map Collection (v1.1.4), so the workaround in https://github.com/highcharts/node-export-server/commit/2d07efcab1ab37660228736a5e6a3196f64be617 is no longer needed.

An additional `;` doesn't break anything as far as I know. To allow backwards compatibility with older Map Collections no action is required here.

I am just adding the info here in case someone has a different usage or finds a problem with doubled `;`.
