### ISSUE TITLE
chart rendering breaks around 5000 x-Axis data points

### ISSUE THREAD

**Issue by bvogel** [highcharts/node-export-server#523]
node v20
highcharts version 10.4.0
export server version: 3.1.1

##### Graph rendered correctly (4999 data points)
![image](https://github.com/highcharts/node-export-server/assets/1853373/8801fbb0-2427-4c55-8aab-a6447c03e841)

##### Graph rendered with increasing errors (5000 data points)
![image](https://github.com/highcharts/node-export-server/assets/1853373/9ab18501-ccb7-48da-90f5-e755d3be9054)

graph don't start at the same point any more

##### Graph broken (5001 data points)
![image](https://github.com/highcharts/node-export-server/assets/1853373/2847af84-62fa-4e41-afc5-82cd9937e666)

graph is missing 3/4 of data

#### Reproduction steps
infiles for the cases:

[working json](https://drive.google.com/file/d/15yjVXNN1sWloHGm6eRBON1m0kO9jvk2_/view?usp=sharing)

[partially broken](https://drive.google.com/file/d/15zf40-IXeGW0Zcgtu3_3rcnL5iVViyak/view?usp=sharing)

[broken](https://drive.google.com/file/d/164PgHQPl7LrCB4SLmzk_16w71sxNIU95/view?usp=sharing)

**Comment by bvogel** [comment]
In the meantime I found out that the error in the second graph may result from unbalanced series lengths, so that error may be expected, however the series have the same length for the third graph and it's still broken

**Comment by bvogel** [comment]
I can add two additional data point for failing data around the 5000 data points mark:

working ([4999 data points](https://drive.google.com/file/d/16A9SSqKM2OBOyckkKU2BiAE3zeDc6_ge/view?usp=sharing))
![image](https://github.com/highcharts/node-export-server/assets/1853373/f3c7db01-96d4-41b9-84ce-f655382d4211)

broken ([5000 data points](https://drive.google.com/file/d/16DayFUvmwKc3SYLrzRdaylnf_HZUxiSs/view?usp=sharing))
![image](https://github.com/highcharts/node-export-server/assets/1853373/22c4c067-7395-460b-8d39-6a0f3099c803)

**Comment by bvogel** [comment]
Thank you, any news on the release date?

**Comment by bvogel** [comment]
Another month has passed, I can't really take this issue as resolved as we can't use the proposed solution - it still hasn't been released yet. Please advise how to proceed. (Due to internal guidelines we aren't in a position to use branches as reference for our packages)

**Comment by bvogel** [comment]
bump!

**Comment by jszuminski** [comment]
@bvogel it has been fixed (on the master branch) and on the official deployed Highcharts Export Server. Please try it out :)

**Comment by bvogel** [comment]
@jszuminski unfortunately we can't use the external server due to company policies, so I'll have to wait for the official release (my test data was deleted already)

**Comment by jszuminski** [comment]
Absolutely, I understand. If you'd like, you can always try to download the package from GitHub.

**Comment by bvogel** [comment]
Hi, I just tested with:
```
INFO 2024-08-08T18:05:17.669282664Z [resource.labels.containerName: highcharts-export-server] Thu Aug 08 2024 18:05:17 GMT+0000 [verbose] - [cache] Fetching script - https://code.highcharts.com/11.4/highcharts-more.js
INFO 2024-08-08T18:05:17.608273297Z [resource.labels.containerName: highcharts-export-server] Thu Aug 08 2024 18:05:17 GMT+0000 [verbose] - [cache] Fetching script - https://code.highcharts.com/11.4/highcharts.js
INFO 2024-08-08T18:05:17.602820134Z [resource.labels.containerName: highcharts-export-server] Thu Aug 08 2024 18:05:17 GMT+0000 [notice] - [cache] Updating cache version to Highcharts: 11.4/.
INFO 2024-08-08T18:05:17.602413336Z [resource.labels.containerName: highcharts-export-server] Thu Aug 08 2024 18:05:17 GMT+0000 [notice] - [cache] Fetching and caching Highcharts dependencies.
INFO 2024-08-08T18:05:17.600292924Z [resource.labels.containerName: highcharts-export-server] Thu Aug 08 2024 18:05:17 GMT+0000 [notice] - [process] Attaching exit listeners to the process.
INFO 2024-08-08T18:05:17.598449415Z [resource.labels.containerName: highcharts-export-server] Starting Highcharts Export Server v4.0.1...
```
but still seeing the same error. 5000 x-axis points will break rendering

**Comment by bvogel** [comment]
i.e. can we have this re-opened please?

**Comment by jszuminski** [comment]
I've reopened this issue and added it to our backlog. If the problem indeed persists (we will have to investigate that), we will try to make it a part of one of the upcoming releases.

**Comment by bvogel** [comment]
Thank you!

**Comment by bvogel** [comment]
@jszuminski were you able to reproduce? should I sent test data from our end?

**Comment by jszuminski** [comment]
@bvogel if possible, you can share the test data, that would be helpful. You can also try to create a minimal reproducible example in JSFiddle, starting from there: https://jsfiddle.net/ftpyxewh/

**Comment by bvogel** [comment]
Hi @jszuminski, 

this fiddle will work as fiddle but is broken if exported through the server https://jsfiddle.net/5ejsu9go/

this one will work: https://jsfiddle.net/j6ns0d3v/

**Comment by bvogel** [comment]
@jszuminski any news on this, were you able to reproduce the error we are seeing?

**Comment by jszuminski** [comment]
@bvogel I seem to have different errors when exporting this, but do not encounter what you encounter. The good news is that this https://github.com/highcharts/node-export-server/pull/561 pull request will introduce many beneficial changes and will allow to detect errors in request/CLI options if they are the ones causing an error so a part of the problem will get solved there; you will get an error or a warning message if the configuration is not optimal or not supported.

However, for now, let's get back to the main problem which is the partial rendering of the line chart. Could you please tell me:
1. Are you sending an HTTP request or are you doing this via CLI? currently, There are separate exporting processes happening; we're currently working on unifying them which will also get rid of this problem.

2. Could you share the full CLI command and a broken `.json` file so that I can 100% get the error that you get? I will then just run the command and share the result with you to compare. If this causes an error on my side as well, I will debug it and get to the root cause.

**Comment by bvogel** [comment]
we use a HTTP POST request, so I have no CLI or json file. The jsfiddles are very close to the requests we send. as mentioned in the previous post we use this code:
```ruby
    def request_chart(for_pdf: false)
      scaling = for_pdf ? 2 : 1
      result = HTTP.post(HIGHCHARTS_EXPORT_SERVER_URL, json: { infile: @chart_options, scale: scaling, type: "jpeg" })

      raise HighchartsError, "status: #{result.status.code} reason: #{result.body}" unless result.status.success?

      StringIO.new(result.body)
    end
```

with the `@chart_options` being 100% identical to the ones in the fiddles. We use Highcharts Export Server v4.0.1 with Highcharts library 11.4.0

**Comment by jszuminski** [comment]
Okay, thank you very much @bvogel! I have successfully managed to reproduce it locally and get the same result as you do:

<img width="1178" alt="Screenshot 2024-09-18 at 09 06 48" src="https://github.com/user-attachments/assets/a2170171-1c3a-4ef2-8027-173e233f22cc">

I will now investigate the cause of the problem by debugging what's going on inside the Puppeteer.

**Comment by bvogel** [comment]
Thank you so much for the update!

**Comment by bvogel** [comment]
@jszuminski any progress on this issue?

**Comment by bvogel** [comment]
@jszuminski mind me reminding you on this issue?
