### ISSUE TITLE
Problems running on AWS Lambda

### ISSUE THREAD

**Issue by davidnoah** [highcharts/node-export-server#81]
LOGS:
Error: write EPIPE
    at exports._errnoException (util.js:1018:11)
    at WriteWrap.afterWrite (net.js:800:14)

I am building a script that dynamically generates an email and also includes a highchart. This script will run as a lambda function for a massive amount of emails, although it seems to fail when I run the node-export-server "export" function. Any idea why this happens? And if so, how can I fix this?

**Comment by mccartney** [comment]
A duplicate of #42

**Comment by mccartney** [comment]
@davidnoah - by any chance are you using a Mac to deploy to Lambda?

I was. And that was the problem. After switching to Linux (for packaging the Lambda deployment package, probably `npm install` is the most relevant here) it worked.

I guess the problem is of some native libraries which one of the dependencies (phantompool?) brings. When deploying from OSX we might be trying to push OSX binaries to AWS Lambda (which is Linux-based).

**Comment by cvasseng** [comment]
Thanks for posting an update on this @mccartney.

That makes a lot of sense - we use the `phantom-prebuilt` package, so if the deployment scripts use the local node modules, you'll end up with a macos build of phantom.js.

**Comment by Keksike** [comment]
Indeed, PhantomJS is by default compiled for the platform where `npm install` is ran.

PhantomJS addresses this issue on the [GitHub README.md here](https://github.com/Medium/phantomjs#cross-platform-repositories).

For me setting the environment variables to:
```
PHANTOMJS_PLATFORM="linux"
PHANTOMJS_ARCH="x64"
```
fixed the issue as I was running phantomjs on AWS Lambda (linux x64) but compiling it on MacOS.

**Comment by azizj1** [comment]
Still experiencing this issue for Node 10.x on AWS Lambda, but not on Node 8.x

**Comment by saurabhjindalFMQ** [comment]
Still experiencing this issue for Node 10.x,12.x on AWS Lambda

**Comment by mccartney** [comment]
@saurabhjindalFMQ are you using Mac to build the Lambda?

**Comment by saurabhjindalFMQ** [comment]
@mccartney I'm using aws codebuild which uses liunx to build the packages. I have tried to build on my local machine linux also but it is not working

**Comment by mccartney** [comment]
OK. Then I don't know. My issue was different.
